// ============================================================
// plugins/copy/copy-button.ts
// ============================================================

const ICON_COPY = '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>';
const ICON_CHECK = '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>';

export function getCopyButtonScript(): string {
    const lines: string[] = [
        `;(function () {`,
        `  var ICON_COPY = '${ICON_COPY}'`,
        `  var ICON_CHECK = '${ICON_CHECK}'`,
        ``,
        `  // ── 剪貼簿工具 ────────────────────────────────────────`,
        `  function fallbackCopy(text) {`,
        `    var ta = document.createElement('textarea')`,
        `    ta.value = text`,
        `    ta.style.cssText = 'position:fixed;left:-9999px;top:-9999px;opacity:0'`,
        `    document.body.appendChild(ta)`,
        `    ta.focus(); ta.select()`,
        `    try { document.execCommand('copy') } catch (e) {}`,
        `    document.body.removeChild(ta)`,
        `  }`,
        `  function copyText(text, onDone) {`,
        `    if (navigator.clipboard && navigator.clipboard.writeText) {`,
        `      navigator.clipboard.writeText(text).then(onDone).catch(function () { fallbackCopy(text); onDone() })`,
        `    } else {`,
        `      fallbackCopy(text); onDone()`,
        `    }`,
        `  }`,
        `  function flashBtn(btn, cells) {`,
        `    btn.innerHTML = ICON_CHECK`,
        `    btn.classList.add('copied')`,
        `    cells.forEach(function (s) { s.classList.add('code-line--flash') })`,
        `    setTimeout(function () {`,
        `      btn.innerHTML = ICON_COPY`,
        `      btn.classList.remove('copied')`,
        `      cells.forEach(function (s) { s.classList.remove('code-line--flash') })`,
        `    }, 1800)`,
        `  }`,
        ``,
        `  // ── 反斜線續行解析（A / line 模式共用）──────────────`,
        `  // 空白行、# 註解略過；行尾 \\ 與下一行合併`,
        `  // 回傳：[{ lines: number[], text: string }, ...]`,
        `  function parseCommands(rawLines) {`,
        `    var cmds = []`,
        `    var i = 0`,
        `    while (i < rawLines.length) {`,
        `      var trimmed = rawLines[i].trimEnd()`,
        `      if (trimmed === '' || /^\\s*#/.test(trimmed)) { i++; continue }`,
        `      var cmdLines = [i]`,
        `      var parts = [trimmed.replace(/\\\\$/, '').trimEnd()]`,
        `      while (/\\\\\\s*$/.test(trimmed)) {`,
        `        i++`,
        `        if (i >= rawLines.length) break`,
        `        trimmed = rawLines[i].trimEnd()`,
        `        if (trimmed === '') break`,
        `        cmdLines.push(i)`,
        `        parts.push(trimmed.replace(/\\\\$/, '').trimEnd())`,
        `      }`,
        `      cmds.push({ lines: cmdLines, text: parts.join(' ') })`,
        `      i++`,
        `    }`,
        `    return cmds`,
        `  }`,
        ``,
        `  // ── # 區段解析（C / cmd 模式）────────────────────────`,
        `  // 遇到 # 開頭行即為區段標題，底下到下一個 # 前的非空指令為該區段內容`,
        `  // 回傳：[{ commentLine: number, comment: string, codeLines: number[], text: string }, ...]`,
        `  function parseSections(rawLines) {`,
        `    var sections = []`,
        `    var i = 0`,
        `    while (i < rawLines.length) {`,
        `      var trimmed = rawLines[i].trim()`,
        `      if (/^#/.test(trimmed)) {`,
        `        var commentLine = i`,
        `        var comment = trimmed.replace(/^#+\\s*/, '')`,
        `        var codeLines = []`,
        `        var codeParts = []`,
        `        i++`,
        `        while (i < rawLines.length && !/^#/.test(rawLines[i].trim())) {`,
        `          var t = rawLines[i].trimEnd()`,
        `          if (t.trim() !== '') {`,
        `            codeLines.push(i)`,
        `            codeParts.push(t.replace(/\\\\$/, '').trimEnd())`,
        `          }`,
        `          i++`,
        `        }`,
        `        if (codeLines.length > 0) {`,
        `          sections.push({ commentLine: commentLine, comment: comment, codeLines: codeLines, text: codeParts.join('\\n') })`,
        `        }`,
        `      } else {`,
        `        i++`,
        `      }`,
        `    }`,
        `    return sections`,
        `  }`,
        ``,
        `  // ── 全局複製按鈕（整塊）──────────────────────────────`,
        `  window.__mdsone_copy = function (container) {`,
        `    container.querySelectorAll('pre').forEach(function (pre) {`,
        `      if (pre.querySelector('.copy-btn')) return`,
        `      var btn = document.createElement('button')`,
        `      btn.className = 'copy-btn'`,
        `      btn.setAttribute('aria-label', 'Copy code')`,
        `      btn.setAttribute('type', 'button')`,
        `      btn.innerHTML = ICON_COPY`,
        `      btn.addEventListener('click', function () {`,
        `        var codeEl = pre.querySelector('code')`,
        `        var codeLines = codeEl ? codeEl.querySelectorAll('.code-line') : null`,
        `        var text = (codeLines && codeLines.length)`,
        `          ? Array.from(codeLines).map(function (s) { return s.textContent }).join('\\n')`,
        `          : (codeEl ? codeEl.textContent : pre.textContent)`,
        `        copyText(text, function () {`,
        `          btn.innerHTML = ICON_CHECK`,
        `          btn.classList.add('copied')`,
        `          setTimeout(function () { btn.innerHTML = ICON_COPY; btn.classList.remove('copied') }, 2000)`,
        `        })`,
        `      })`,
        `      pre.appendChild(btn)`,
        `    })`,
        `  }`,
        ``,
        `  // ── A 模式：行複製（--code-copy line）────────────────`,
        `  window.__mdsone_line_copy = function (container) {`,
        `    container.querySelectorAll('pre').forEach(function (pre) {`,
        `      if (pre.dataset.lineCopyReady) return`,
        `      pre.dataset.lineCopyReady = '1'`,
        `      var codeEl = pre.querySelector('code')`,
        `      if (!codeEl) return`,
        `      var rawLines = (codeEl.textContent || '').split('\\n')`,
        `      if (rawLines[rawLines.length - 1] === '') rawLines.pop()`,
        `      var cmds = parseCommands(rawLines)`,
        `      if (cmds.length === 0) return`,
        `      var lineToCmd = {}`,
        `      cmds.forEach(function (cmd) {`,
        `        cmd.lines.forEach(function (li) { lineToCmd[li] = cmd })`,
        `      })`,
        `      var htmlLines = codeEl.innerHTML.split('\\n')`,
        `      if (htmlLines[htmlLines.length - 1] === '') htmlLines.pop()`,
        `      codeEl.innerHTML = htmlLines.map(function (lineHTML, idx) {`,
        `        var cmd = lineToCmd[idx]`,
        `        if (!cmd) return '<span class="code-line">' + (lineHTML || '\\u200b') + '</span>'`,
        `        var isFirst = cmd.lines[0] === idx`,
        `        return (`,
        `          '<span class="code-line code-line--cmd' + (isFirst ? '' : ' code-line--cont') +`,
        `          '" data-cmd="' + encodeURIComponent(cmd.text) + '">' +`,
        `          (lineHTML || '\\u200b') +`,
        `          (isFirst ? '<button class="line-copy-btn" type="button" aria-label="Copy command">' + ICON_COPY + '</button>' : '') +`,
        `          '</span>'`,
        `        )`,
        `      }).join('')`,
        `      codeEl.addEventListener('click', function (e) {`,
        `        var btn = e.target.closest('.line-copy-btn')`,
        `        if (!btn) return`,
        `        var span = btn.closest('.code-line--cmd')`,
        `        if (!span) return`,
        `        var text = decodeURIComponent(span.dataset.cmd || '')`,
        `        if (!text) return`,
        `        e.stopPropagation()`,
        `        copyText(text, function () {`,
        `          flashBtn(btn, Array.from(codeEl.querySelectorAll('[data-cmd="' + span.dataset.cmd + '"]')))`,
        `        })`,
        `      })`,
        `      codeEl.addEventListener('mouseover', function (e) {`,
        `        var span = e.target.closest('.code-line--cmd')`,
        `        if (!span) return`,
        `        codeEl.querySelectorAll('[data-cmd="' + span.dataset.cmd + '"]').forEach(function (s) { s.classList.add('code-line--hover') })`,
        `      })`,
        `      codeEl.addEventListener('mouseout', function (e) {`,
        `        var span = e.target.closest('.code-line--cmd')`,
        `        if (!span) return`,
        `        codeEl.querySelectorAll('[data-cmd="' + span.dataset.cmd + '"]').forEach(function (s) { s.classList.remove('code-line--hover') })`,
        `      })`,
        `    })`,
        `  }`,
        ``,
        `  // ── C 模式：區段複製（--code-copy cmd）───────────────`,
        `  // # 註解行右側顯示複製按鈕，複製底下到下一個 # 前的所有指令`,
        `  window.__mdsone_cmd_copy = function (container) {`,
        `    container.querySelectorAll('pre').forEach(function (pre) {`,
        `      if (pre.dataset.cmdCopyReady) return`,
        `      pre.dataset.cmdCopyReady = '1'`,
        `      var codeEl = pre.querySelector('code')`,
        `      if (!codeEl) return`,
        `      var rawLines = (codeEl.textContent || '').split('\\n')`,
        `      if (rawLines[rawLines.length - 1] === '') rawLines.pop()`,
        `      var sections = parseSections(rawLines)`,
        `      if (sections.length === 0) return`,
        `      // 建立 commentLine → section、codeLine → secId 映射`,
        `      var lineToSection = {}`,
        `      var lineToSecId = {}`,
        `      sections.forEach(function (sec, idx) {`,
        `        lineToSection[sec.commentLine] = sec`,
        `        sec.codeLines.forEach(function (li) { lineToSecId[li] = idx })`,
        `      })`,
        `      var htmlLines = codeEl.innerHTML.split('\\n')`,
        `      if (htmlLines[htmlLines.length - 1] === '') htmlLines.pop()`,
        `      codeEl.innerHTML = htmlLines.map(function (lineHTML, idx) {`,
        `        var sec = lineToSection[idx]`,
        `        if (sec) {`,
        `          var secIdx = sections.indexOf(sec)`,
        `          return (`,
        `            '<span class="code-line code-line--sec-head" data-sec="' + encodeURIComponent(sec.text) + '" data-sec-id="' + secIdx + '">' +`,
        `            '<span class="sec-comment">' + (lineHTML || '\\u200b') + '</span>' +`,
        `            '<button class="sec-copy-btn" type="button" aria-label="Copy section">' + ICON_COPY + '</button>' +`,
        `            '</span>'`,
        `          )`,
        `        }`,
        `        var sid = lineToSecId[idx]`,
        `        if (sid !== undefined) {`,
        `          return '<span class="code-line code-line--sec-code" data-sec-id="' + sid + '">' + (lineHTML || '\\u200b') + '</span>'`,
        `        }`,
        `        return '<span class="code-line">' + (lineHTML || '\\u200b') + '</span>'`,
        `      }).join('')`,
        `      codeEl.addEventListener('click', function (e) {`,
        `        var btn = e.target.closest('.sec-copy-btn')`,
        `        if (!btn) return`,
        `        var head = btn.closest('.code-line--sec-head')`,
        `        if (!head) return`,
        `        var text = decodeURIComponent(head.dataset.sec || '')`,
        `        if (!text) return`,
        `        e.stopPropagation()`,
        `        var sid = head.dataset.secId`,
        `        var codeCells = Array.from(codeEl.querySelectorAll('.code-line--sec-code[data-sec-id="' + sid + '"]'))`,
        `        copyText(text, function () { flashBtn(btn, codeCells) })`,
        `      })`,
        `      // hover：hover 到註解行或代碼行都高亮整個區段，並讓複製按鈕顯示`,
        `      function getSecId(el) {`,
        `        var head = el.closest('.code-line--sec-head')`,
        `        if (head) return head.dataset.secId`,
        `        var code = el.closest('.code-line--sec-code')`,
        `        if (code) return code.dataset.secId`,
        `        return null`,
        `      }`,
        `      codeEl.addEventListener('mouseover', function (e) {`,
        `        var sid = getSecId(e.target)`,
        `        if (sid === null) return`,
        `        var head = codeEl.querySelector('.code-line--sec-head[data-sec-id="' + sid + '"]')`,
        `        if (head) head.classList.add('sec-active')`,
        `        codeEl.querySelectorAll('.code-line--sec-code[data-sec-id="' + sid + '"]').forEach(function (s) { s.classList.add('code-line--hover') })`,
        `      })`,
        `      codeEl.addEventListener('mouseout', function (e) {`,
        `        var sid = getSecId(e.target)`,
        `        if (sid === null) return`,
        `        var head = codeEl.querySelector('.code-line--sec-head[data-sec-id="' + sid + '"]')`,
        `        if (head) head.classList.remove('sec-active')`,
        `        codeEl.querySelectorAll('.code-line--sec-code[data-sec-id="' + sid + '"]').forEach(function (s) { s.classList.remove('code-line--hover') })`,
        `      })`,
        `    })`,
        `  }`,
        `})()`,
    ];
    return lines.join("\n");
}

/** A 模式 CSS */
export function getLineCopyStyle(): string {
    return [
        `.code-line { display: block; position: relative; line-height: inherit; margin: 0; padding: 0; }`,
        `.code-line--cmd {`,
        `  border-radius: 3px;`,
        `  padding-right: 2rem;`,
        `  transition: background 0.12s;`,
        `}`,
        `.code-line--hover { background: rgba(128,128,128,0.12); }`,
        `.code-line--flash { background: rgba(55,138,221,0.18) !important; }`,
        `.line-copy-btn {`,
        `  position: absolute;`,
        `  right: 4px;`,
        `  top: 50%;`,
        `  transform: translateY(-50%);`,
        `  display: inline-flex;`,
        `  align-items: center;`,
        `  justify-content: center;`,
        `  width: 22px; height: 22px;`,
        `  padding: 0; border: none; border-radius: 4px;`,
        `  background: transparent; color: inherit;`,
        `  opacity: 0; cursor: pointer;`,
        `  transition: opacity 0.15s, background 0.12s;`,
        `}`,
        `.code-line--cmd:hover .line-copy-btn,`,
        `.line-copy-btn.copied { opacity: 0.75; }`,
        `.line-copy-btn:hover { opacity: 1 !important; background: rgba(128,128,128,0.18); }`,
    ].join("\n");
}

/** C 模式 CSS */
export function getCmdCopyStyle(): string {
    return [
        `.code-line { display: block; position: relative; line-height: inherit; margin: 0; padding: 0; }`,
        `.code-line--sec-head {`,
        `  display: flex;`,
        `  align-items: center;`,
        `  line-height: inherit;`,
        `  gap: 6px;`,
        `  border-radius: 3px;`,
        `  transition: background 0.12s;`,
        `}`,
        `.sec-comment {`,
        `  flex: 1 1 0;`,
        `  min-width: 0;`,
        `  overflow: hidden;`,
        `  text-overflow: ellipsis;`,
        `  white-space: nowrap;`,
        `  line-height: inherit;`,
        `}`,
        `.code-line--flash { background: rgba(55,138,221,0.18) !important; }`,
        `.sec-copy-btn {`,
        `  flex: 0 0 auto;`,
        `  display: inline-flex;`,
        `  align-items: center;`,
        `  justify-content: center;`,
        `  width: 1.4em; height: 1.4em;`,
        `  padding: 0; border: none; border-radius: 4px;`,
        `  background: transparent; color: inherit;`,
        `  opacity: 0; cursor: pointer;`,
        `  transition: opacity 0.15s, background 0.12s;`,
        `}`,
        `.code-line--sec-head:hover .sec-copy-btn,`,
        `.code-line--sec-head.sec-active .sec-copy-btn,`,
        `.sec-copy-btn.copied { opacity: 0.75; }`,
        `.sec-copy-btn:hover { opacity: 1 !important; background: rgba(128,128,128,0.18); }`,
    ].join("\n");
}
