import { defineConfig } from "tsup";

export default defineConfig([
  // CLI entry
  {
    entry: { cli: "src/cli/main.ts" },
    format: ["esm"],
    outDir: "dist",
    target: "node18",
    platform: "node",
    banner: { js: "#!/usr/bin/env node" },
    splitting: false,
    clean: true,
    dts: false,
    sourcemap: true,
    // Keep runtime deps external.
    external: [
      "@modelcontextprotocol/sdk",
      "@iarna/toml",
      "commander",
      "html-minifier-terser",
      "katex",
      "markdown-it",
      "markdown-it-attrs",
      "markdown-it-katex",
      "zod",
    ],
  },
  // Core library entry (pure functions, zero I/O)
  {
    entry: { index: "src/core/index.ts" },
    format: ["esm"],
    outDir: "dist",
    target: "node18",
    platform: "node",
    splitting: false,
    clean: false,
    dts: true,
    sourcemap: true,
    external: [
      "@modelcontextprotocol/sdk",
      "html-minifier-terser",
      "katex",
      "markdown-it",
      "markdown-it-attrs",
      "markdown-it-katex",
      "zod",
    ],
  },
  // Node adapter entry (I/O layer)
  {
    entry: { node: "src/adapters/node/index.ts" },
    format: ["esm"],
    outDir: "dist",
    target: "node18",
    platform: "node",
    splitting: false,
    clean: false,
    dts: true,
    sourcemap: true,
    external: [
      "@modelcontextprotocol/sdk",
      "@iarna/toml",
      "commander",
      "html-minifier-terser",
      "katex",
      "markdown-it",
      "markdown-it-attrs",
      "markdown-it-katex",
      "zod",
    ],
  },
  // Plugin entries (each plugin owns its own public API)
  {
    entry: {
      "plugins/code-highlight": "plugins/code-highlight/index.ts",
      "plugins/katex": "plugins/katex/index.ts",
      "plugins/code-copy": "plugins/code-copy/index.ts",
      "plugins/image": "plugins/image/index.ts",
      "plugins/code-line-number": "plugins/code-line-number/index.ts",
      "plugins/minify": "plugins/minify/index.ts",
    },
    format: ["esm"],
    outDir: "dist",
    target: "node18",
    platform: "node",
    splitting: false,
    clean: false,
    dts: true,
    sourcemap: true,
    external: [
      "@modelcontextprotocol/sdk",
      "@shikijs/markdown-exit",
      "@shikijs/markdown-exit/core",
      "cheerio",
      "highlight.js",
      "shiki",
      "sharp",
      "html-minifier-terser",
      "katex",
      "markdown-it",
      "markdown-it-attrs",
      "markdown-it-katex",
      "zod",
    ],
  },
]);
